export const symbolsList = [
  { icon: '1', data: '1' },
  { icon: '2', data: '2' },
  { icon: '3', data: '3' },
  { icon: '4', data: '4' },
  { icon: '5', data: '5' },
  { icon: '6', data: '6' },
  { icon: '7', data: '7' },
  { icon: '8', data: '8' },
  { icon: '9', data: '9' },
  { icon: '0', data: '0' },
  { icon: '.', data: '.' },
  { icon: ',', data: ',' },
  { icon: '+', data: '+' },
  { icon: '-', data: '-' },
  { icon: '×', data: '\\times' },
  { icon: '÷', data: '\\div' },
  { icon: '=', data: '=' },
  { icon: '≠', data: '\\neq' },
  { icon: '(', data: '(' },
  { icon: ')', data: ')' },
  { icon: '[', data: '[' },
  { icon: ']', data: ']' },
  { icon: '{', data: '\\{' },
  { icon: '}', data: '\\}' },
  { icon: '<', data: '<' },
  { icon: '>', data: '>' },
  { icon: 'x', data: 'x' },
  { icon: 'y', data: 'y' },
  { icon: 'a', data: 'a' },
  { icon: 'b', data: 'b' },
  { icon: 'n', data: 'n' },
  { icon: '²', data: '^2' },
  { icon: '³', data: '^3' },
  { icon: 'ⁿ', data: '^{n}' },
  { icon: '|', data: '|' },
  { icon: '√', data: '\\sqrt{✀}' },
  { icon: '∛', data: '\\sqrt[3]{✀}' },
  { icon: '½', data: '\\frac{1}{2}' },
  { icon: '⅓', data: '\\frac{1}{3}' },
  { icon: '¼', data: '\\frac{1}{4}' },
  { icon: 'a/b', data: '\\frac{✀}{✀}' },
  { icon: '^', data: '^{✀}' },
  { icon: '_', data: '_{✀}' },
  { icon: '%', data: '\\%' },
  { icon: 'π', data: '\\pi' },
  { icon: '∞', data: '\\infty' },
  { icon: '°', data: '^{\\circ}' },
  { icon: '≤', data: '\\leq' },
  { icon: '≥', data: '\\geq' },
  { icon: '±', data: '\\pm' },
  { icon: '≈', data: '\\approx' },
  { icon: '→', data: '\\rightarrow' },
  { icon: '⇒', data: '\\Rightarrow' },
  { icon: 'f(x)', data: 'f(x)' },
  { icon: 'sin', data: '\\sin ✀' },
  { icon: 'cos', data: '\\cos ✀' },
  { icon: 'tg', data: '\\tan ✀' },
  { icon: 'log', data: '\\log ✀' },
  { icon: 'ln', data: '\\ln ✀' },
  { icon: 'lim', data: '\\lim_{✀}' },
  { icon: '∫', data: '\\int' },
  { icon: 'dx', data: 'dx' },
  { icon: 'Σ', data: '\\sum' },
  { icon: '∏', data: '\\prod' },
  { icon: '∠', data: '\\angle' },
  { icon: '!', data: '!' },
  { icon: 'e', data: 'e' },
  { icon: 'α', data: '\\alpha' },
  { icon: 'β', data: '\\beta' },
  { icon: 'γ', data: '\\gamma' }
]
