image: node:20

stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -y && apt-get install -y sshpass rsync openssh-client
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 95.46.96.179 >> ~/.ssh/known_hosts

    # Faqat kerakli fayllarni yuborish
    - sshpass -p "$SERVER_PASSWORD" rsync -az --delete --exclude=node_modules --exclude=.git --exclude=.next --exclude=npm-debug.log -e "ssh -o StrictHostKeyChecking=no" ./ root@95.46.96.179:/var/www/iqmath_student

    # Serverda node, npm, pm2 bilan ishlash (dev rejim)
    - >
      sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@95.46.96.179 '
        export NVM_DIR="$HOME/.nvm";
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
        nvm use 20;
        cd /var/www/iqmath_student &&
        npm install --legacy-peer-deps --prefer-offline --no-audit --progress=false &&
        pm2 restart iqmath_student || pm2 start npm --name "iqmath_student" -- run dev &&
        pm2 save
      '
