export const KEYS = {
  login: 'login',
  register: 'register',
  studentProfile: 'studentProfile',
  teacherProfile: 'teacherProfile',
  olimpiadaQuizList: 'olimpiadaQuizList',
  quizTest: 'quizTest',
  submitAnswers: 'submitAnswers',
  recieveCode: 'recieveCode',
  resultQuiz: 'resultQuiz',
  resendSMSCode: 'resendSMSCode',
  forgetPassword: 'forgetPassword',
  resendSMSCodeForget: 'resendSMSCodeForget',
  registerDate: 'registerDate',
  faqs: 'faqs',
  networkings: 'networkings',
  documents: 'documents',
  ofertas: 'ofertas',
  banner: 'banner',
  beforeReminder: 'beforeReminder',
  afterReminder: 'afterReminder',
  schoolClasses: 'schoolClasses',
  studentSubjects: 'studentSubjects',
  teacherSubjects: 'teacherSubjects',
  teacherStudents: 'teacherStudents',
  teacherGroups: 'teacherGroups',
  // Student list keys
  studentList: 'studentList',
  studentChapters: 'studentChapters',
  studentTopics: 'studentTopics',
  studentQuestions: 'studentQuestions',
  coins: 'coins',
  teacherCoins: 'teacherCoins',
  subscription: 'subscription',
  advisedTopics: 'advisedTopics',
  levelStatistics: 'levelStatistics',
  diagnosticsTopics: 'diagnosticsTopics',
  diagnosticSubjects: 'diagnosticSubjects',
  recommendations: 'recommendations',
  systemSettings: 'systemSettings',
  systemFaqs: 'systemFaqs',
  statistics: 'statistics',
  studentStatistics: 'studentStatistics',
  studentSubjectChapters: 'studentSubjectChapters',
  // Teacher subjects keys
  chapters: 'chapters',
  topics: 'topics',
  questionList: 'questionList',
  // Teacher reward keys
  teacherReward: 'teacherReward',
  teacherRewardList: 'teacherRewardList',
  
  // Friends keys
  friends: 'friends',
  friendInvites: 'friend-invites',
  inviteLink: 'invite-link',
  myReferrals: 'my-referrals',
  products: 'products',
  exchangeProduct: 'exchange-product',
  
  // Parents Management keys
  parentsList: 'parentsList',
  studentsList: 'studentsList',
  createParent: 'createParent',
  
  // Mentor requests keys
  mentorRequests: 'mentorRequests'
}
